### ISSUE TITLE
camera.txt

### ISSUE THREAD

**Issue by yrcrcy** [UditSinghParihar/RoRD#10]
Hello,  thank you for your contributions!
I want to ask: [RoRD/evaluation/DiverseView/evalRT py]. The camera.txt is the need to generate? It is still provided by you, if I use the file you provided, but I did not find the camera.txt.

**Comment by UditSinghParihar** [comment]
Hi,
Thanks for pointing out the missing `camera.txt`. We have uploaded [`camera.txt`](https://github.com/UditSinghParihar/RoRD/blob/main/configs/camera.txt) in the config folder. 

Also, we have made changes to ease the process of evaluation and visualization in the latest commit. So you may want to pull the latest changes. You can find the instructions for evaluation on the `DiverseView` dataset in the [README.md](https://github.com/UditSinghParihar/RoRD#evaluation-on-diverseview-dataset).

Do let us know if this works for you.

Regards,
Udit
