### ISSUE TITLE
use model_test for training

### ISSUE THREAD

**Issue by atomishcv** [UditSinghParihar/RoRD#12]
as the title say, can i use the d2-net in model_test for training?

**Comment by UditSinghParihar** [comment]
No, `model_test` is for inference only, you cant use it for training. For training the RoRD look into https://github.com/UditSinghParihar/RoRD#training-rord-on-phototourism-images

For training D2Net, check here: https://github.com/mihaidusmanu/d2-net#training

**Comment by atomishcv** [comment]
thank you very much!
