### ISSUE TITLE
train the network

### ISSUE THREAD

**Issue by zzkslam** [UditSinghParihar/RoRD#3]
Can you tell me how to train the network?

**Comment by UditSinghParihar** [comment]
Hi,
    We are currently refactoring our codebase, we would update regarding training the network in a week.

**Comment by UditSinghParihar** [comment]
Hi,
    You can find instructions for downloading phototourism dataset and running the training script using rotational homographies in the [README.md](https://github.com/UditSinghParihar/RoRD#training-rord-on-phototourism-images).   

Regards,
Udit
