### ISSUE TITLE
Details on creating a custom dataset for training.

### ISSUE THREAD

**Issue by 1995YogeshSharma** [UditSinghParihar/RoRD#9]
Hi @UditSinghParihar, 

I have gone through the Readme and instructions work well for training on given dataset.

I am looking to generate a custom dataset and train on that. Can you please add more detail on the same (like how to annotate, format of data, do we need to modify some code etc)?

Thanks!

**Comment by UditSinghParihar** [comment]
Hi,
1. If you want to provide custom correspondences, then you should change [self.getGrid](https://github.com/UditSinghParihar/RoRD/blob/main/lib/dataloaders/datasetPhotoTourism_ipr.py#L140) function in our data loader. This function basically returns ground-truth correspondences for the image pair. Here our correspondences are related by a homography, but it can also be related via some other way like warping using depth and poses, as done originally in [D2Net](https://github.com/mihaidusmanu/d2-net/issues/60).    
2. If you want to change our data loader, then you should obtain pos1 key points using the same [upscale_positions](https://github.com/UditSinghParihar/RoRD/blob/main/lib/dataloaders/datasetPhotoTourism_ipr.py#L58) function as currently there inside `self.getGrid` function, while pos2 would be generated using your way of obtaining correspondences for pos1, in our case we are warping pos1 using ground-truth homography to generate pos2.

Regards,
Udit
